"""
Benchmark test set of 100 well-characterized proteins (+10 backups) for evaluating
ProstT5 inverse folding (3Di -> amino acid sequence).

Selection criteria:
- All Swiss-Prot (reviewed) entries with AlphaFoldDB predicted structures
- Length range: 50-2500 residues
- Diversity across length, secondary structure, organism, MSA depth, function

Length bins (20 each): tiny (50-100), short (101-250), medium (251-500),
                       long (501-1000), very_long (1001-2500)

Targets: ~25 each for SS class (all_alpha, all_beta, alpha_beta, coil_rich)
         ~25 each for organism (human, model_organism, bacteria, archaea_other)
"""

from dataclasses import dataclass


@dataclass
class TestProtein:
    uniprot_id: str
    name: str
    length: int
    organism: str
    length_bin: str  # "tiny"|"short"|"medium"|"long"|"very_long"
    ss_class: str  # "all_alpha"|"all_beta"|"alpha_beta"|"coil_rich"
    organism_bin: str  # "human"|"model_organism"|"bacteria"|"archaea_other"
    function: str  # "enzyme"|"structural"|"signaling"|"membrane"|"dna_rna_binding"|"transport"|"immune"|"storage"|"other"
    fold_complexity: str  # "single_domain"|"multi_domain"
    msa_depth: str  # "deep"|"moderate"|"shallow"
    disease_associated: bool
    notes: str = ""


# =============================================================================
# BENCHMARK TEST SET - 100 proteins
# =============================================================================

TEST_SET: list[TestProtein] = [
    # =========================================================================
    # TINY BIN (50-100 residues) - proteins 1-20
    # =========================================================================
    TestProtein(
        uniprot_id="P62990",
        name="Ubiquitin",
        length=76,
        organism="Homo sapiens",
        length_bin="tiny",
        ss_class="alpha_beta",
        organism_bin="human",
        function="signaling",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="Beta-grasp fold; most conserved eukaryotic protein",
    ),
    TestProtein(
        uniprot_id="P01308",
        name="Insulin",
        length=110,
        organism="Homo sapiens",
        length_bin="tiny",
        ss_class="all_alpha",
        organism_bin="human",
        function="signaling",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="Preproinsulin; all-alpha; disulfide-bonded; diabetes",
    ),
    TestProtein(
        uniprot_id="P02798",
        name="Metallothionein-2",
        length=61,
        organism="Homo sapiens",
        length_bin="tiny",
        ss_class="coil_rich",
        organism_bin="human",
        function="storage",
        fold_complexity="single_domain",
        msa_depth="moderate",
        disease_associated=False,
        notes="20 Cys/61 residues; extreme AA bias; metal detox; minimal 2ndary structure",
    ),
    TestProtein(
        uniprot_id="P62944",
        name="FKBP12",
        length=108,
        organism="Homo sapiens",
        length_bin="tiny",
        ss_class="all_beta",
        organism_bin="human",
        function="enzyme",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="FK506/rapamycin receptor; beta-sheet-rich immunophilin",
    ),
    TestProtein(
        uniprot_id="P01542",
        name="Insulin-like growth factor I",
        length=70,
        organism="Homo sapiens",
        length_bin="tiny",
        ss_class="all_alpha",
        organism_bin="human",
        function="signaling",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="Helical growth factor; insulin superfamily",
    ),
    TestProtein(
        uniprot_id="P43408",
        name="Rubredoxin",
        length=54,
        organism="Desulfovibrio vulgaris",
        length_bin="tiny",
        ss_class="all_beta",
        organism_bin="bacteria",
        function="transport",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="Fe-S electron carrier; beta-knot fold",
    ),
    TestProtein(
        uniprot_id="P0AFL6",
        name="Cold shock protein CspC",
        length=69,
        organism="Escherichia coli",
        length_bin="tiny",
        ss_class="all_beta",
        organism_bin="bacteria",
        function="dna_rna_binding",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="OB-fold; five-stranded beta-barrel; RNA chaperone",
    ),
    TestProtein(
        uniprot_id="P0ACJ8",
        name="Acyl carrier protein",
        length=78,
        organism="Escherichia coli",
        length_bin="tiny",
        ss_class="all_alpha",
        organism_bin="bacteria",
        function="enzyme",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="Four-helix bundle; phosphopantetheine; fatty acid synthesis",
    ),
    TestProtein(
        uniprot_id="P0A988",
        name="HU-alpha",
        length=90,
        organism="Escherichia coli",
        length_bin="tiny",
        ss_class="alpha_beta",
        organism_bin="bacteria",
        function="dna_rna_binding",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="Histone-like; bacterial nucleoid compaction",
    ),
    TestProtein(
        uniprot_id="P0A7Y4",
        name="50S ribosomal protein L33",
        length=55,
        organism="Escherichia coli",
        length_bin="tiny",
        ss_class="alpha_beta",
        organism_bin="bacteria",
        function="structural",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="Zinc ribbon fold; conserved in bacteria",
    ),
    TestProtein(
        uniprot_id="Q57733",
        name="Rubredoxin",
        length=53,
        organism="Methanopyrus kandleri",
        length_bin="tiny",
        ss_class="all_beta",
        organism_bin="archaea_other",
        function="transport",
        fold_complexity="single_domain",
        msa_depth="moderate",
        disease_associated=False,
        notes="Hyperthermophilic archaeon; Fe-S; Tm >170C",
    ),
    TestProtein(
        uniprot_id="P22579",
        name="Sac7d",
        length=66,
        organism="Sulfolobus acidocaldarius",
        length_bin="tiny",
        ss_class="all_beta",
        organism_bin="archaea_other",
        function="dna_rna_binding",
        fold_complexity="single_domain",
        msa_depth="moderate",
        disease_associated=False,
        notes="Archaeal chromatin; SH3-like beta-barrel; thermostable scaffold",
    ),
    TestProtein(
        uniprot_id="P15378",
        name="Rubredoxin",
        length=54,
        organism="Clostridium pasteurianum",
        length_bin="tiny",
        ss_class="all_beta",
        organism_bin="bacteria",
        function="transport",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="First rubredoxin crystal structure; model protein",
    ),
    TestProtein(
        uniprot_id="P34690",
        name="Ubiquitin (UBQ-1)",
        length=76,
        organism="Caenorhabditis elegans",
        length_bin="tiny",
        ss_class="alpha_beta",
        organism_bin="model_organism",
        function="signaling",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="C. elegans ubiquitin; identical fold to human; model organism",
    ),
    TestProtein(
        uniprot_id="P0A7U3",
        name="30S ribosomal protein S19",
        length=92,
        organism="Escherichia coli",
        length_bin="tiny",
        ss_class="alpha_beta",
        organism_bin="bacteria",
        function="structural",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="30S-50S bridge protein",
    ),
    TestProtein(
        uniprot_id="P63165",
        name="SUMO-1",
        length=101,
        organism="Homo sapiens",
        length_bin="tiny",
        ss_class="alpha_beta",
        organism_bin="human",
        function="signaling",
        fold_complexity="single_domain",
        msa_depth="moderate",
        disease_associated=True,
        notes="Ubiquitin-like modifier; beta-grasp fold",
    ),
    TestProtein(
        uniprot_id="P0A7N4",
        name="50S ribosomal protein L30",
        length=58,
        organism="Escherichia coli",
        length_bin="tiny",
        ss_class="alpha_beta",
        organism_bin="bacteria",
        function="structural",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="Conserved bacterial ribosomal protein",
    ),
    TestProtein(
        uniprot_id="P24311",
        name="Cytochrome c",
        length=108,
        organism="Saccharomyces cerevisiae",
        length_bin="tiny",
        ss_class="all_alpha",
        organism_bin="model_organism",
        function="transport",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="Yeast iso-1-cytochrome c; all-alpha; electron transport; deeply conserved",
    ),
    TestProtein(
        uniprot_id="P56252",
        name="Thioredoxin",
        length=105,
        organism="Methanobacterium thermoautotrophicum",
        length_bin="tiny",
        ss_class="alpha_beta",
        organism_bin="archaea_other",
        function="enzyme",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="Archaeal thioredoxin; deeply conserved fold across all domains of life",
    ),
    TestProtein(
        uniprot_id="P18253",
        name="Histone H2A.Z",
        length=99,
        organism="Drosophila melanogaster",
        length_bin="tiny",
        ss_class="all_alpha",
        organism_bin="model_organism",
        function="dna_rna_binding",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="Histone variant; all-alpha; chromatin regulation; fly model",
    ),
    # =========================================================================
    # SHORT BIN (101-250 residues) - proteins 21-40
    # =========================================================================
    TestProtein(
        uniprot_id="A0A6G0XC32",
        name="Bat coronavirus spike fragment",
        length=163,
        organism="Rhinolophus affinis coronavirus",
        length_bin="short",
        ss_class="all_beta",
        organism_bin="archaea_other",
        function="other",
        fold_complexity="single_domain",
        msa_depth="shallow",
        disease_associated=True,
        notes="Existing entry; viral; shallow MSA",
    ),
    TestProtein(
        uniprot_id="P42212",
        name="Green fluorescent protein (GFP)",
        length=238,
        organism="Aequorea victoria",
        length_bin="short",
        ss_class="all_beta",
        organism_bin="archaea_other",
        function="other",
        fold_complexity="single_domain",
        msa_depth="shallow",
        disease_associated=False,
        notes="Beta-barrel; autocatalytic chromophore; jellyfish; shallow MSA",
    ),
    TestProtein(
        uniprot_id="P61626",
        name="Lysozyme C",
        length=148,
        organism="Homo sapiens",
        length_bin="short",
        ss_class="all_alpha",
        organism_bin="human",
        function="enzyme",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="All-alpha; innate immunity; amyloidosis variants",
    ),
    TestProtein(
        uniprot_id="P68871",
        name="Hemoglobin subunit beta",
        length=147,
        organism="Homo sapiens",
        length_bin="short",
        ss_class="all_alpha",
        organism_bin="human",
        function="transport",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="Globin fold; sickle cell (E6V); thalassemia",
    ),
    TestProtein(
        uniprot_id="P37840",
        name="Alpha-synuclein",
        length=140,
        organism="Homo sapiens",
        length_bin="short",
        ss_class="coil_rich",
        organism_bin="human",
        function="other",
        fold_complexity="single_domain",
        msa_depth="moderate",
        disease_associated=True,
        notes="Intrinsically disordered; Parkinson's; amyloid-forming",
    ),
    TestProtein(
        uniprot_id="P02686",
        name="Myelin basic protein",
        length=197,
        organism="Homo sapiens",
        length_bin="short",
        ss_class="coil_rich",
        organism_bin="human",
        function="structural",
        fold_complexity="single_domain",
        msa_depth="moderate",
        disease_associated=True,
        notes="Intrinsically disordered; myelin compaction; MS autoantigen",
    ),
    TestProtein(
        uniprot_id="P61769",
        name="Beta-2-microglobulin",
        length=119,
        organism="Homo sapiens",
        length_bin="short",
        ss_class="all_beta",
        organism_bin="human",
        function="immune",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="Ig fold; MHC-I light chain; dialysis amyloidosis",
    ),
    TestProtein(
        uniprot_id="P00720",
        name="T4 lysozyme",
        length=164,
        organism="Enterobacteria phage T4",
        length_bin="short",
        ss_class="all_alpha",
        organism_bin="archaea_other",
        function="enzyme",
        fold_complexity="single_domain",
        msa_depth="shallow",
        disease_associated=False,
        notes="Protein engineering workhorse; phage = limited MSA",
    ),
    TestProtein(
        uniprot_id="P0ABH7",
        name="Dihydrofolate reductase (DHFR)",
        length=159,
        organism="Escherichia coli",
        length_bin="short",
        ss_class="alpha_beta",
        organism_bin="bacteria",
        function="enzyme",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="Antifolate target; Rossmann-like fold; deeply conserved",
    ),
    TestProtein(
        uniprot_id="P0A9Q7",
        name="Adenylate kinase",
        length=214,
        organism="Escherichia coli",
        length_bin="short",
        ss_class="alpha_beta",
        organism_bin="bacteria",
        function="enzyme",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="NMP kinase; large lid-domain conformational change",
    ),
    TestProtein(
        uniprot_id="P0A953",
        name="Flavodoxin-1",
        length=176,
        organism="Escherichia coli",
        length_bin="short",
        ss_class="alpha_beta",
        organism_bin="bacteria",
        function="transport",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="FMN-binding; alpha/beta/alpha sandwich",
    ),
    TestProtein(
        uniprot_id="P00698",
        name="HEWL (Hen egg-white lysozyme)",
        length=147,
        organism="Gallus gallus",
        length_bin="short",
        ss_class="all_alpha",
        organism_bin="archaea_other",
        function="enzyme",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="First enzyme structure solved (1965); 4 disulfides",
    ),
    TestProtein(
        uniprot_id="P0DP27",
        name="Calmodulin-1",
        length=149,
        organism="Mus musculus",
        length_bin="short",
        ss_class="all_alpha",
        organism_bin="model_organism",
        function="signaling",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="Mouse calmodulin; EF-hand; all-alpha; Ca2+ sensor",
    ),
    TestProtein(
        uniprot_id="P62937",
        name="Cyclophilin A",
        length=165,
        organism="Homo sapiens",
        length_bin="short",
        ss_class="all_beta",
        organism_bin="human",
        function="enzyme",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="Beta-barrel PPIase; cyclosporin binding",
    ),
    TestProtein(
        uniprot_id="P10599",
        name="Thioredoxin",
        length=105,
        organism="Homo sapiens",
        length_bin="short",
        ss_class="alpha_beta",
        organism_bin="human",
        function="enzyme",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="Thioredoxin fold; universally conserved redox protein",
    ),
    TestProtein(
        uniprot_id="P56201",
        name="Superoxide reductase",
        length=124,
        organism="Pyrococcus furiosus",
        length_bin="short",
        ss_class="alpha_beta",
        organism_bin="archaea_other",
        function="enzyme",
        fold_complexity="single_domain",
        msa_depth="moderate",
        disease_associated=False,
        notes="Archaeal iron enzyme; O2 detox in anaerobes; novel fold",
    ),
    TestProtein(
        uniprot_id="P16949",
        name="Stathmin-1",
        length=149,
        organism="Homo sapiens",
        length_bin="short",
        ss_class="coil_rich",
        organism_bin="human",
        function="structural",
        fold_complexity="single_domain",
        msa_depth="moderate",
        disease_associated=True,
        notes="Microtubule-destabilizing; largely disordered when free; coiled-coil when bound",
    ),
    TestProtein(
        uniprot_id="P68082",
        name="Myoglobin (sperm whale)",
        length=154,
        organism="Physeter catodon",
        length_bin="short",
        ss_class="all_alpha",
        organism_bin="archaea_other",
        function="transport",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="First protein structure solved (Kendrew 1958); globin fold",
    ),
    TestProtein(
        uniprot_id="P63101",
        name="14-3-3 protein zeta/delta",
        length=245,
        organism="Mus musculus",
        length_bin="short",
        ss_class="all_alpha",
        organism_bin="model_organism",
        function="signaling",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="Mouse 14-3-3; all-alpha helical groove; phospho-Ser/Thr binding; conserved",
    ),
    TestProtein(
        uniprot_id="Q9R0Q7",
        name="Prostaglandin E synthase 3 (p23)",
        length=160,
        organism="Mus musculus",
        length_bin="short",
        ss_class="alpha_beta",
        organism_bin="model_organism",
        function="enzyme",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="Mouse p23/PTGES3; thioredoxin-like fold; HSP90 co-chaperone",
    ),
    # =========================================================================
    # MEDIUM BIN (251-500 residues) - proteins 41-60
    # =========================================================================
    TestProtein(
        uniprot_id="P04637",
        name="Tumor protein p53",
        length=393,
        organism="Homo sapiens",
        length_bin="medium",
        ss_class="alpha_beta",
        organism_bin="human",
        function="dna_rna_binding",
        fold_complexity="multi_domain",
        msa_depth="moderate",
        disease_associated=True,
        notes="Existing entry; guardian of genome; structured + disordered",
    ),
    TestProtein(
        uniprot_id="P0DTC9",
        name="SARS-CoV-2 Nucleocapsid",
        length=419,
        organism="SARS-CoV-2",
        length_bin="medium",
        ss_class="coil_rich",
        organism_bin="archaea_other",
        function="dna_rna_binding",
        fold_complexity="multi_domain",
        msa_depth="shallow",
        disease_associated=True,
        notes="Existing entry; viral; disordered linkers; shallow MSA",
    ),
    TestProtein(
        uniprot_id="P0AEX9",
        name="Maltose-binding protein (MBP)",
        length=396,
        organism="Escherichia coli",
        length_bin="medium",
        ss_class="alpha_beta",
        organism_bin="bacteria",
        function="transport",
        fold_complexity="multi_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="Two-domain periplasmic protein; fusion/crystallization tag",
    ),
    TestProtein(
        uniprot_id="P00918",
        name="Carbonic anhydrase 2",
        length=260,
        organism="Homo sapiens",
        length_bin="medium",
        ss_class="all_beta",
        organism_bin="human",
        function="enzyme",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="10-stranded beta-sheet; zinc; glaucoma target (acetazolamide)",
    ),
    TestProtein(
        uniprot_id="P0A855",
        name="Triosephosphate isomerase (TIM)",
        length=255,
        organism="Escherichia coli",
        length_bin="medium",
        ss_class="alpha_beta",
        organism_bin="bacteria",
        function="enzyme",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="TIM barrel archetype; catalytically perfect enzyme",
    ),
    TestProtein(
        uniprot_id="P00784",
        name="Papain",
        length=345,
        organism="Carica papaya",
        length_bin="medium",
        ss_class="alpha_beta",
        organism_bin="archaea_other",
        function="enzyme",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="Cysteine protease archetype; Cys-His-Asn triad",
    ),
    TestProtein(
        uniprot_id="P69441",
        name="Alcohol dehydrogenase 1",
        length=347,
        organism="Saccharomyces cerevisiae",
        length_bin="medium",
        ss_class="alpha_beta",
        organism_bin="model_organism",
        function="enzyme",
        fold_complexity="multi_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="Yeast ADH; Rossmann fold; fermentation",
    ),
    TestProtein(
        uniprot_id="P02572",
        name="Actin (Act5C)",
        length=376,
        organism="Drosophila melanogaster",
        length_bin="medium",
        ss_class="alpha_beta",
        organism_bin="model_organism",
        function="structural",
        fold_complexity="multi_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="Fly actin; extremely conserved cytoskeletal protein",
    ),
    TestProtein(
        uniprot_id="P63244",
        name="RACK1",
        length=317,
        organism="Homo sapiens",
        length_bin="medium",
        ss_class="all_beta",
        organism_bin="human",
        function="signaling",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="WD40 7-bladed beta-propeller; scaffold",
    ),
    TestProtein(
        uniprot_id="P00439",
        name="Phenylalanine hydroxylase (PAH)",
        length=452,
        organism="Homo sapiens",
        length_bin="medium",
        ss_class="alpha_beta",
        organism_bin="human",
        function="enzyme",
        fold_complexity="multi_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="PKU; iron hydroxylase; regulatory + catalytic + tetramerization",
    ),
    TestProtein(
        uniprot_id="P62593",
        name="TEM-1 beta-lactamase",
        length=286,
        organism="Escherichia coli",
        length_bin="medium",
        ss_class="alpha_beta",
        organism_bin="bacteria",
        function="enzyme",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="Antibiotic resistance; directed evolution workhorse",
    ),
    TestProtein(
        uniprot_id="P00766",
        name="Chymotrypsinogen A",
        length=262,
        organism="Bos taurus",
        length_bin="medium",
        ss_class="all_beta",
        organism_bin="archaea_other",
        function="enzyme",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="Serine protease; two beta-barrel domains",
    ),
    TestProtein(
        uniprot_id="P0A6P9",
        name="Elongation factor Tu",
        length=394,
        organism="Escherichia coli",
        length_bin="medium",
        ss_class="alpha_beta",
        organism_bin="bacteria",
        function="other",
        fold_complexity="multi_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="GTPase; three domains; 5-10% of total E. coli protein",
    ),
    TestProtein(
        uniprot_id="P04406",
        name="GAPDH",
        length=335,
        organism="Homo sapiens",
        length_bin="medium",
        ss_class="alpha_beta",
        organism_bin="human",
        function="enzyme",
        fold_complexity="multi_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="Rossmann fold; glycolysis; moonlighting in apoptosis",
    ),
    TestProtein(
        uniprot_id="P24941",
        name="CDK2",
        length=298,
        organism="Homo sapiens",
        length_bin="medium",
        ss_class="alpha_beta",
        organism_bin="human",
        function="enzyme",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="Cell cycle kinase; bilobal fold; >400 crystal structures",
    ),
    TestProtein(
        uniprot_id="P02994",
        name="Elongation factor 1-alpha",
        length=458,
        organism="Saccharomyces cerevisiae",
        length_bin="medium",
        ss_class="alpha_beta",
        organism_bin="model_organism",
        function="other",
        fold_complexity="multi_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="GTPase; translation; deeply conserved; yeast model",
    ),
    TestProtein(
        uniprot_id="P61583",
        name="Indole-3-glycerol phosphate synthase",
        length=262,
        organism="Sulfolobus solfataricus",
        length_bin="medium",
        ss_class="alpha_beta",
        organism_bin="archaea_other",
        function="enzyme",
        fold_complexity="single_domain",
        msa_depth="moderate",
        disease_associated=False,
        notes="Archaeal TIM barrel; thermostable; Trp biosynthesis",
    ),
    TestProtein(
        uniprot_id="P05089",
        name="Arginase-1",
        length=330,
        organism="Homo sapiens",
        length_bin="medium",
        ss_class="alpha_beta",
        organism_bin="human",
        function="enzyme",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="Mn metalloenzyme; urea cycle; hyperargininemia",
    ),
    TestProtein(
        uniprot_id="P07688",
        name="Cathepsin B",
        length=339,
        organism="Homo sapiens",
        length_bin="medium",
        ss_class="alpha_beta",
        organism_bin="human",
        function="enzyme",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="Lysosomal cysteine protease; papain-like fold; cancer metastasis",
    ),
    TestProtein(
        uniprot_id="P06280",
        name="Alpha-galactosidase A",
        length=429,
        organism="Homo sapiens",
        length_bin="medium",
        ss_class="alpha_beta",
        organism_bin="human",
        function="enzyme",
        fold_complexity="multi_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="Fabry disease; TIM barrel + beta-sandwich; lysosomal enzyme",
    ),
    # =========================================================================
    # LONG BIN (501-1000 residues) - proteins 61-80
    # =========================================================================
    TestProtein(
        uniprot_id="P19367",
        name="Hexokinase-1",
        length=917,
        organism="Homo sapiens",
        length_bin="long",
        ss_class="alpha_beta",
        organism_bin="human",
        function="enzyme",
        fold_complexity="multi_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="Two-domain glucose kinase; hemolytic anemia; 917 residues",
    ),
    TestProtein(
        uniprot_id="P0A6F5",
        name="GroEL (Chaperonin 60)",
        length=548,
        organism="Escherichia coli",
        length_bin="long",
        ss_class="alpha_beta",
        organism_bin="bacteria",
        function="other",
        fold_complexity="multi_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="Chaperonin; three domains; heptameric ring; protein folding",
    ),
    TestProtein(
        uniprot_id="P02768",
        name="Serum albumin",
        length=609,
        organism="Homo sapiens",
        length_bin="long",
        ss_class="all_alpha",
        organism_bin="human",
        function="transport",
        fold_complexity="multi_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="All-alpha; 3 homologous domains; most abundant plasma protein",
    ),
    TestProtein(
        uniprot_id="P08684",
        name="CYP3A4",
        length=503,
        organism="Homo sapiens",
        length_bin="long",
        ss_class="all_alpha",
        organism_bin="human",
        function="enzyme",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="P450 fold; metabolizes ~50% of drugs; all-alpha; ER membrane",
    ),
    TestProtein(
        uniprot_id="P35354",
        name="COX-2",
        length=604,
        organism="Homo sapiens",
        length_bin="long",
        ss_class="all_alpha",
        organism_bin="human",
        function="enzyme",
        fold_complexity="multi_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="Cyclooxygenase; celecoxib target; inflammation",
    ),
    TestProtein(
        uniprot_id="P04150",
        name="Glucocorticoid receptor",
        length=777,
        organism="Homo sapiens",
        length_bin="long",
        ss_class="coil_rich",
        organism_bin="human",
        function="dna_rna_binding",
        fold_complexity="multi_domain",
        msa_depth="moderate",
        disease_associated=True,
        notes="Nuclear receptor; ~50% disordered NTD; zinc DBD + alpha LBD",
    ),
    TestProtein(
        uniprot_id="P0AG67",
        name="Ribosomal protein S1",
        length=557,
        organism="Escherichia coli",
        length_bin="long",
        ss_class="all_beta",
        organism_bin="bacteria",
        function="structural",
        fold_complexity="multi_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="Six tandem OB-fold domains; largest ribosomal protein",
    ),
    TestProtein(
        uniprot_id="P15056",
        name="B-Raf",
        length=766,
        organism="Homo sapiens",
        length_bin="long",
        ss_class="alpha_beta",
        organism_bin="human",
        function="enzyme",
        fold_complexity="multi_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="V600E melanoma; vemurafenib; RAS-MAPK pathway",
    ),
    TestProtein(
        uniprot_id="P05067",
        name="APP (Amyloid precursor protein)",
        length=770,
        organism="Homo sapiens",
        length_bin="long",
        ss_class="alpha_beta",
        organism_bin="human",
        function="membrane",
        fold_complexity="multi_domain",
        msa_depth="moderate",
        disease_associated=True,
        notes="Alzheimer's disease; type I TM; source of amyloid-beta",
    ),
    TestProtein(
        uniprot_id="P0ABB0",
        name="ATP synthase alpha subunit",
        length=513,
        organism="Escherichia coli",
        length_bin="long",
        ss_class="alpha_beta",
        organism_bin="bacteria",
        function="enzyme",
        fold_complexity="multi_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="F1-ATPase; deeply conserved rotary motor",
    ),
    TestProtein(
        uniprot_id="P23246",
        name="SFPQ",
        length=707,
        organism="Homo sapiens",
        length_bin="long",
        ss_class="coil_rich",
        organism_bin="human",
        function="dna_rna_binding",
        fold_complexity="multi_domain",
        msa_depth="moderate",
        disease_associated=True,
        notes="Paraspeckle; largely disordered; coiled-coil + RRM",
    ),
    TestProtein(
        uniprot_id="P21802",
        name="FGFR2",
        length=821,
        organism="Homo sapiens",
        length_bin="long",
        ss_class="alpha_beta",
        organism_bin="human",
        function="signaling",
        fold_complexity="multi_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="Apert/Crouzon syndrome; Ig + kinase domains",
    ),
    TestProtein(
        uniprot_id="P11413",
        name="G6PD",
        length=515,
        organism="Homo sapiens",
        length_bin="long",
        ss_class="alpha_beta",
        organism_bin="human",
        function="enzyme",
        fold_complexity="multi_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="Most common enzymopathy; Rossmann fold; NADPH production",
    ),
    TestProtein(
        uniprot_id="P07901",
        name="HSP90-alpha (mouse)",
        length=733,
        organism="Mus musculus",
        length_bin="long",
        ss_class="alpha_beta",
        organism_bin="model_organism",
        function="other",
        fold_complexity="multi_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="Mouse HSP90; chaperone; 3 domains; cancer drug target model",
    ),
    TestProtein(
        uniprot_id="Q02880",
        name="DNA topoisomerase 2-beta",
        length=621,
        organism="Homo sapiens",
        length_bin="long",
        ss_class="alpha_beta",
        organism_bin="human",
        function="enzyme",
        fold_complexity="multi_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="Type II topoisomerase; doxorubicin target; ATPase + DNA binding",
    ),
    TestProtein(
        uniprot_id="P14598",
        name="NOX2",
        length=570,
        organism="Homo sapiens",
        length_bin="long",
        ss_class="all_alpha",
        organism_bin="human",
        function="enzyme",
        fold_complexity="multi_domain",
        msa_depth="moderate",
        disease_associated=True,
        notes="NADPH oxidase; chronic granulomatous disease; 6 TM + DH domain",
    ),
    TestProtein(
        uniprot_id="P10591",
        name="HSP70 (SSA1)",
        length=642,
        organism="Saccharomyces cerevisiae",
        length_bin="long",
        ss_class="alpha_beta",
        organism_bin="model_organism",
        function="other",
        fold_complexity="multi_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="Yeast HSP70; NBD + SBD; deeply conserved chaperone; model for Hsp70 family",
    ),
    TestProtein(
        uniprot_id="P61869",
        name="Beta-galactosidase",
        length=525,
        organism="Thermus thermophilus",
        length_bin="long",
        ss_class="alpha_beta",
        organism_bin="archaea_other",
        function="enzyme",
        fold_complexity="multi_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="Thermophilic enzyme; TIM barrel; extremophile",
    ),
    TestProtein(
        uniprot_id="P10275",
        name="Androgen receptor",
        length=919,
        organism="Homo sapiens",
        length_bin="long",
        ss_class="coil_rich",
        organism_bin="human",
        function="dna_rna_binding",
        fold_complexity="multi_domain",
        msa_depth="moderate",
        disease_associated=True,
        notes="Prostate cancer; SBMA; ~60% disordered NTD + DBD + LBD",
    ),
    TestProtein(
        uniprot_id="P00832",
        name="ATP synthase subunit beta (mitochondrial)",
        length=529,
        organism="Saccharomyces cerevisiae",
        length_bin="long",
        ss_class="alpha_beta",
        organism_bin="model_organism",
        function="enzyme",
        fold_complexity="multi_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="Yeast F1-ATPase catalytic subunit; rotary motor; deeply conserved",
    ),
    # =========================================================================
    # VERY LONG BIN (1001-2500 residues) - proteins 81-100
    # =========================================================================
    TestProtein(
        uniprot_id="P38398",
        name="BRCA1",
        length=1863,
        organism="Homo sapiens",
        length_bin="very_long",
        ss_class="coil_rich",
        organism_bin="human",
        function="dna_rna_binding",
        fold_complexity="multi_domain",
        msa_depth="moderate",
        disease_associated=True,
        notes="Tumor suppressor; ~70% disordered; RING + BRCT domains",
    ),
    TestProtein(
        uniprot_id="P02452",
        name="Collagen alpha-1(I)",
        length=1464,
        organism="Homo sapiens",
        length_bin="very_long",
        ss_class="coil_rich",
        organism_bin="human",
        function="structural",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="Triple helix; 33% Gly; polyproline II; osteogenesis imperfecta",
    ),
    TestProtein(
        uniprot_id="P12821",
        name="ACE",
        length=1306,
        organism="Homo sapiens",
        length_bin="very_long",
        ss_class="all_alpha",
        organism_bin="human",
        function="enzyme",
        fold_complexity="multi_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="ACE inhibitor target; two zinc metalloprotease domains; all-alpha",
    ),
    TestProtein(
        uniprot_id="P00968",
        name="Carbamoyl-phosphate synthase (large chain)",
        length=1073,
        organism="Escherichia coli",
        length_bin="very_long",
        ss_class="alpha_beta",
        organism_bin="bacteria",
        function="enzyme",
        fold_complexity="multi_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="Ammonia tunnel; four domains; deeply conserved",
    ),
    TestProtein(
        uniprot_id="P42336",
        name="PIK3CA (PI3K p110alpha)",
        length=1068,
        organism="Homo sapiens",
        length_bin="very_long",
        ss_class="alpha_beta",
        organism_bin="human",
        function="enzyme",
        fold_complexity="multi_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="Most mutated oncogene; lipid kinase; alpelisib target",
    ),
    TestProtein(
        uniprot_id="P42345",
        name="mTOR",
        length=2549,
        organism="Homo sapiens",
        length_bin="very_long",
        ss_class="all_alpha",
        organism_bin="human",
        function="enzyme",
        fold_complexity="multi_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="HEAT + FAT + kinase; rapamycin/everolimus target",
    ),
    TestProtein(
        uniprot_id="P0DTC2",
        name="SARS-CoV-2 Spike protein",
        length=1273,
        organism="SARS-CoV-2",
        length_bin="very_long",
        ss_class="alpha_beta",
        organism_bin="archaea_other",
        function="membrane",
        fold_complexity="multi_domain",
        msa_depth="shallow",
        disease_associated=True,
        notes="COVID-19 vaccine antigen; trimeric; RBD + S2; shallow viral MSA",
    ),
    TestProtein(
        uniprot_id="P13569",
        name="CFTR",
        length=1480,
        organism="Homo sapiens",
        length_bin="very_long",
        ss_class="all_alpha",
        organism_bin="human",
        function="membrane",
        fold_complexity="multi_domain",
        msa_depth="moderate",
        disease_associated=True,
        notes="Cystic fibrosis; ABC transporter; deltaF508; trikafta",
    ),
    TestProtein(
        uniprot_id="O60885",
        name="BRD4",
        length=1362,
        organism="Homo sapiens",
        length_bin="very_long",
        ss_class="coil_rich",
        organism_bin="human",
        function="dna_rna_binding",
        fold_complexity="multi_domain",
        msa_depth="moderate",
        disease_associated=True,
        notes="BET protein; ~75% disordered; JQ1/BET inhibitor target",
    ),
    TestProtein(
        uniprot_id="P06756",
        name="Integrin alpha-V",
        length=1048,
        organism="Homo sapiens",
        length_bin="very_long",
        ss_class="all_beta",
        organism_bin="human",
        function="membrane",
        fold_complexity="multi_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="Cell adhesion; beta-propeller + thigh + calf; RGD-binding",
    ),
    TestProtein(
        uniprot_id="P04626",
        name="HER2/ErbB2",
        length=1255,
        organism="Homo sapiens",
        length_bin="very_long",
        ss_class="alpha_beta",
        organism_bin="human",
        function="signaling",
        fold_complexity="multi_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="Breast cancer; trastuzumab target; constitutively active RTK",
    ),
    TestProtein(
        uniprot_id="Q13936",
        name="Cav1.2 (CACNA1C)",
        length=2138,
        organism="Homo sapiens",
        length_bin="very_long",
        ss_class="all_alpha",
        organism_bin="human",
        function="membrane",
        fold_complexity="multi_domain",
        msa_depth="moderate",
        disease_associated=True,
        notes="L-type Ca2+ channel; 24 TM helices; Timothy syndrome",
    ),
    TestProtein(
        uniprot_id="P02458",
        name="Collagen alpha-1(II)",
        length=1487,
        organism="Homo sapiens",
        length_bin="very_long",
        ss_class="coil_rich",
        organism_bin="human",
        function="structural",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="Cartilage collagen; Gly-X-Y repeats; Stickler syndrome",
    ),
    TestProtein(
        uniprot_id="Q61410",
        name="mTOR (mouse)",
        length=2549,
        organism="Mus musculus",
        length_bin="very_long",
        ss_class="all_alpha",
        organism_bin="model_organism",
        function="enzyme",
        fold_complexity="multi_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="Mouse mTOR; rapamycin target; aging research model",
    ),
    TestProtein(
        uniprot_id="P13368",
        name="Drosophila EGFR (DER)",
        length=1394,
        organism="Drosophila melanogaster",
        length_bin="very_long",
        ss_class="alpha_beta",
        organism_bin="model_organism",
        function="signaling",
        fold_complexity="multi_domain",
        msa_depth="moderate",
        disease_associated=False,
        notes="Fly EGFR; developmental patterning; four ligands",
    ),
    TestProtein(
        uniprot_id="P04808",
        name="Vitellogenin-2",
        length=1614,
        organism="Caenorhabditis elegans",
        length_bin="very_long",
        ss_class="alpha_beta",
        organism_bin="model_organism",
        function="storage",
        fold_complexity="multi_domain",
        msa_depth="moderate",
        disease_associated=False,
        notes="Yolk protein; lipid transport; worm aging biomarker",
    ),
    TestProtein(
        uniprot_id="Q04721",
        name="Notch 2",
        length=2471,
        organism="Homo sapiens",
        length_bin="very_long",
        ss_class="all_beta",
        organism_bin="human",
        function="signaling",
        fold_complexity="multi_domain",
        msa_depth="moderate",
        disease_associated=True,
        notes="EGF repeats + LNR + ankyrin; Alagille syndrome",
    ),
    TestProtein(
        uniprot_id="P07949",
        name="RET",
        length=1114,
        organism="Homo sapiens",
        length_bin="very_long",
        ss_class="alpha_beta",
        organism_bin="human",
        function="signaling",
        fold_complexity="multi_domain",
        msa_depth="moderate",
        disease_associated=True,
        notes="MEN2/medullary thyroid cancer; cadherin-like + kinase",
    ),
    TestProtein(
        uniprot_id="P35498",
        name="Nav1.1 (SCN1A)",
        length=2009,
        organism="Homo sapiens",
        length_bin="very_long",
        ss_class="all_alpha",
        organism_bin="human",
        function="membrane",
        fold_complexity="multi_domain",
        msa_depth="moderate",
        disease_associated=True,
        notes="Na+ channel; Dravet syndrome epilepsy; 24 TM helices",
    ),
    TestProtein(
        uniprot_id="P00533",
        name="EGFR",
        length=1210,
        organism="Homo sapiens",
        length_bin="very_long",
        ss_class="alpha_beta",
        organism_bin="human",
        function="signaling",
        fold_complexity="multi_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="Existing entry; receptor tyrosine kinase; lung cancer target",
    ),
]


# =============================================================================
# BACKUP PROTEINS (10 entries)
# =============================================================================

BACKUP_SET: list[TestProtein] = [
    TestProtein(
        uniprot_id="P0A7L0",
        name="50S ribosomal protein L27",
        length=84,
        organism="Escherichia coli",
        length_bin="tiny",
        ss_class="alpha_beta",
        organism_bin="bacteria",
        function="structural",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="Backup; peptidyl transferase center",
    ),
    TestProtein(
        uniprot_id="P01375",
        name="TNF-alpha",
        length=233,
        organism="Homo sapiens",
        length_bin="short",
        ss_class="all_beta",
        organism_bin="human",
        function="signaling",
        fold_complexity="single_domain",
        msa_depth="moderate",
        disease_associated=True,
        notes="Backup; jelly-roll fold; anti-TNF biologics target",
    ),
    TestProtein(
        uniprot_id="P62988",
        name="NEDD8",
        length=81,
        organism="Homo sapiens",
        length_bin="tiny",
        ss_class="alpha_beta",
        organism_bin="human",
        function="signaling",
        fold_complexity="single_domain",
        msa_depth="moderate",
        disease_associated=True,
        notes="Backup; ubiquitin-like; cullin neddylation",
    ),
    TestProtein(
        uniprot_id="P00441",
        name="SOD1",
        length=154,
        organism="Homo sapiens",
        length_bin="short",
        ss_class="all_beta",
        organism_bin="human",
        function="enzyme",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="Backup; ALS mutations; Greek-key beta-barrel",
    ),
    TestProtein(
        uniprot_id="P00517",
        name="PKA C-alpha (bovine)",
        length=351,
        organism="Bos taurus",
        length_bin="medium",
        ss_class="alpha_beta",
        organism_bin="archaea_other",
        function="enzyme",
        fold_complexity="multi_domain",
        msa_depth="deep",
        disease_associated=False,
        notes="Backup; first kinase structure (1991); prototype",
    ),
    TestProtein(
        uniprot_id="P04040",
        name="Catalase",
        length=527,
        organism="Homo sapiens",
        length_bin="long",
        ss_class="alpha_beta",
        organism_bin="human",
        function="enzyme",
        fold_complexity="multi_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="Backup; heme; H2O2 detox; acatalasemia",
    ),
    TestProtein(
        uniprot_id="P22303",
        name="Acetylcholinesterase",
        length=614,
        organism="Homo sapiens",
        length_bin="long",
        ss_class="alpha_beta",
        organism_bin="human",
        function="enzyme",
        fold_complexity="single_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="Backup; alpha/beta hydrolase; donepezil target",
    ),
    TestProtein(
        uniprot_id="P11362",
        name="FGFR1",
        length=822,
        organism="Homo sapiens",
        length_bin="long",
        ss_class="alpha_beta",
        organism_bin="human",
        function="signaling",
        fold_complexity="multi_domain",
        msa_depth="deep",
        disease_associated=True,
        notes="Backup; RTK; Pfeiffer syndrome; erdafitinib",
    ),
    TestProtein(
        uniprot_id="Q9NZC2",
        name="TREM2",
        length=230,
        organism="Homo sapiens",
        length_bin="short",
        ss_class="all_beta",
        organism_bin="human",
        function="immune",
        fold_complexity="single_domain",
        msa_depth="moderate",
        disease_associated=True,
        notes="Backup; Ig V-type; Alzheimer's risk (R47H); microglia",
    ),
    TestProtein(
        uniprot_id="P54289",
        name="CACNA2D1",
        length=1091,
        organism="Homo sapiens",
        length_bin="very_long",
        ss_class="alpha_beta",
        organism_bin="human",
        function="membrane",
        fold_complexity="multi_domain",
        msa_depth="moderate",
        disease_associated=True,
        notes="Backup; gabapentin target; neuropathic pain",
    ),
]


# Convenience accessors
TEST_IDS: list[str] = [p.uniprot_id for p in TEST_SET]
BACKUP_IDS: list[str] = [p.uniprot_id for p in BACKUP_SET]

# Combined full set
FULL_BENCHMARK: list[TestProtein] = TEST_SET + BACKUP_SET


def print_summary():
    """Print a summary of the benchmark set composition."""
    from collections import Counter

    print(f"Total proteins: {len(FULL_BENCHMARK)} "
          f"({len(TEST_SET)} main + {len(BACKUP_SET)} backup)")
    print(f"Unique UniProt IDs in main set: {len(set(p.uniprot_id for p in TEST_SET))}")
    print()

    print("=" * 60)
    print("MAIN SET COMPOSITION")
    print("=" * 60)

    bins = Counter(p.length_bin for p in TEST_SET)
    print("\nLength bins:")
    for b in ["tiny", "short", "medium", "long", "very_long"]:
        print(f"  {b}: {bins.get(b, 0)}")

    ss = Counter(p.ss_class for p in TEST_SET)
    print("\nSecondary structure classes:")
    for s in ["all_alpha", "all_beta", "alpha_beta", "coil_rich"]:
        print(f"  {s}: {ss.get(s, 0)}")

    org = Counter(p.organism_bin for p in TEST_SET)
    print("\nOrganism bins:")
    for o in ["human", "model_organism", "bacteria", "archaea_other"]:
        print(f"  {o}: {org.get(o, 0)}")

    msa = Counter(p.msa_depth for p in TEST_SET)
    print("\nMSA depth:")
    for m in ["deep", "moderate", "shallow"]:
        print(f"  {m}: {msa.get(m, 0)}")

    func = Counter(p.function for p in TEST_SET)
    print("\nFunctions:")
    for f, c in func.most_common():
        print(f"  {f}: {c}")

    dis = sum(1 for p in TEST_SET if p.disease_associated)
    print(f"\nDisease-associated: {dis}/{len(TEST_SET)}")

    fold = Counter(p.fold_complexity for p in TEST_SET)
    print("\nFold complexity:")
    for f in ["single_domain", "multi_domain"]:
        print(f"  {f}: {fold.get(f, 0)}")

    lengths = [p.length for p in TEST_SET]
    print(f"\nLength range: {min(lengths)}-{max(lengths)} residues")

    existing = {"P01308", "A0A6G0XC32", "P04637", "P0DTC9", "P00533"}
    found = {p.uniprot_id for p in TEST_SET} & existing
    print(f"\nRequired proteins found: {len(found)}/5 "
          f"({', '.join(sorted(found))})")

    # Check for proteins with "Replaced" in notes
    replaced = [p for p in TEST_SET if "eplaced" in p.notes]
    if replaced:
        print(f"\nWARNING: {len(replaced)} entries still have 'Replaced' notes:")
        for p in replaced:
            print(f"  {p.uniprot_id} - {p.name}: {p.notes}")


if __name__ == "__main__":
    print_summary()
